export const ROUTES = {
  BASE: "/",
  ARTICLE_ROUTES: "/api/news",
  USER_ROUTES: "/api/user",
  CATEGORY_ROUTES: "/api/category",
  COMMENT_ROUTES: "/api/comments",
  IMAGES_ROUTES: "/api/images",
  IMAGES_ROUTE: "/images",
  ARTICLE: {
    GET_UNPUBLISHED_ARTICLES: "/unpublished",
    GET_ARTICLE_BY_URL: "/:newsUrl",
    GET_ARTICLES_BY_CATEGORY_URL: "/category/:categoryUrl",
    GET_POPULAR_ARTICLES: "/popular",
    PUBLISH_ARTICLE: "/publish/:id",
    DELETE_ARTICLE: "/delete/:id",
    UPDATE_ARTICLE: "/update/:id",
    TOGGLE_LIKE: "/like/:id",
    TOGGLE_COMMENT: "/comment/:id",
  },
  USER: {
    REGISTER: "/register",
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forgot-password",
    RESTORE_PASSWORD: "/restore-password",
    CHECK_PASSWORD: "/check-password",
    UPDATE_USER: "/update-user",
    DELETE_USER: "/delete-user",
    TOGGLE_BLOCK_USER: "/block-user",
    LOGOUT: "/logout",
    GET_USER: "/me",
    GET_ALL_USERS: "/all",
    GET_ACCESS_TOKEN_BY_REFRESH_TOKEN: "/token",
  },
  CATEGORY: {
    GET_ALL_CATEGORIES: "/all",
    DELETE: "/delete-category/:id",
    GET_ACTIVE_CATEGORIES: "/active",
  },
  COMMENT: {
    GET_COMMENTS_BY_ARTICLE_ID: "/article/:articleId",
    GET_UNPUBLISHED_COMMENTS: "/unpublished",
    PUBLISH_COMMENT: "/publish/:id",
    DELETE_COMMENT: "/:id",
  },
  IMAGES: {
    UPLOAD: "/upload",
  },
};
